# ChemoSpec2D

```{r,echo=FALSE,message=FALSE}
library("ChemoSpec2D")
```

## calcLvls
```{r, message=FALSE, warning = FALSE, error = FALSE}

set.seed(9)
MM <- matrix(runif(100, -1, 1), nrow = 10) # test data
tsts <- c("even", "log", "poslog", "exp", "posexp", "ecdf", "NMR")
for (i in 1:length(tsts)) {
	nl <- 10
	if(tsts[i] == "ecdf")  nl <- seq(0.1, 0.9, 0.1)
	levels <- calcLvls(M = MM, n = nl, mode = tsts[i],
   showHist = TRUE, main = tsts[i])
	}


```

## centscaleSpectra2D
```{r, message=FALSE, warning = FALSE, error = FALSE}

data(MUD1)
tst <- centscaleSpectra2D(MUD1)

```











## inspectLvls
```{r, message=FALSE, warning = FALSE, error = FALSE}

data(MUD1)
inspectLvls(MUD1, ylim = c(0, 50), main = "All MUD1 Data, mode = even")
inspectLvls(MUD1, ylim = c(0, 50), mode = "NMR",  main = "All MUD1 Data, mode = NMR")

```



## miaSpectra2D
```{r, message=FALSE, warning = FALSE, error = FALSE}

data(MUD1)
res <- miaSpectra2D(MUD1)
plotScores(MUD1, res, main = "MIA Scores", tol = 0.1, ellipse = "cls")
plotScree(res)
MUD1a <- miaLoadings(MUD1, res, load_lvls = c(-0.4, -0.2, 0.2, 0.4),
  main = "MIA Comp. 1 Loadings")

# Selection of loading matrix levels can be aided by the following

inspectLvls(MUD1a, loadings = TRUE, ylim = c(0, 10),
  main = "Histogram of Loadings Matrix")

```

## MUD1
```{r, message=FALSE, warning = FALSE, error = FALSE}

data(MUD1)
sumSpectra(MUD1)

```

## normSpectra2D
```{r, message=FALSE, warning = FALSE, error = FALSE}

data(MUD1)
MUD1n <- normSpectra2D(MUD1)
MUD1b <- removeFreq(MUD1, remF2 = 2.5 ~ 3.5)
MUD1bn <- normSpectra2D(MUD1b)

```



## pfacSpectra2D
```{r, message=FALSE, warning = FALSE, error = FALSE}

data(MUD1)
set.seed(123)
res <- pfacSpectra2D(MUD1, parallel = FALSE, nfac = 2)
plotScores(MUD1, res, tol = 0.1, leg.loc = "topright",
  ellipse = "cls", main = "PARAFAC Score Plot")
res1 <- pfacLoadings(MUD1, res,
  load_lvls = seq(-12, -2, 2),
  main = "PARAFAC Comp. 1 Loadings")
res2 <- pfacLoadings(MUD1, res, load_lvls = seq(-12, -2, 2),
  ref = 2, ref_lvls = c(-0.2, -0.1, 0.1, 0.2),
  ref_cols = c("violet", "violet", "orange", "orange"),
  main = "PARAFAC Comp. 1 Loadings + Ref. Spectrum")

# Selection of loading matrix levels can be aided by the following

inspectLvls(res1, loadings = TRUE, ylim = c(0, 50),
  main = "Histogram of Loadings Matrix")

```





## plotSlice
```{r, message=FALSE, warning = FALSE, error = FALSE}

data(MUD1)
plotSlice(MUD1, F1 = 25, main = "Slice @ F1 = 25 ppm")

```

## plotSpectra2D
```{r, message=FALSE, warning = FALSE, error = FALSE}

data(MUD1)
mylvls <- seq(-0.3, 0.3, 0.1)[-4]
plotSpectra2D(MUD1, which = 7, lvls = mylvls,
  main = "MUD1 Sample 7")
plotSpectra2D(MUD1, which = c(1, 6), lvls = list(mylvls, mylvls),
  cols = list(rep("black", 6), rep("red", 6)),
  main = "MUD1 Sample 1 (black) & Sample 6 (red)")

```





## removePeaks2D
```{r, message=FALSE, warning = FALSE, error = FALSE}
# Note we will set contours a bit low to better
# show what is going on.

data(MUD1)
mylvls <- seq(-0.3, 0.3, 0.1)
mylvls[4] <- 0.05

plotSpectra2D(MUD1, which = 7, lvls = mylvls,
  main = "MUD1 Sample 7: Complete Data Set")

MUD1a <- removePeaks2D(MUD1, remF2 = 2.5 ~ 4)
sumSpectra(MUD1a)
plotSpectra2D(MUD1a, which = 7, lvls = mylvls,
  main = "MUD1 Sample 7\\nRemoved Peaks: F2 2.5 ~ 4")

MUD1b <- removePeaks2D(MUD1, remF2 = low ~ 5)
sumSpectra(MUD1b)
plotSpectra2D(MUD1b, which = 7, lvls = mylvls,
  main = "MUD1 Sample 7\\nRemoved Peaks: F2 low ~ 5")

MUD1c <- removePeaks2D(MUD1, remF1 = high ~ 23)
sumSpectra(MUD1c)
plotSpectra2D(MUD1c, which = 7, lvls = mylvls,
  main = "MUD1 Sample 7\\nRemoved Peaks: F1 high ~ 23")

MUD1d <- removePeaks2D(MUD1, remF2 = 2.5 ~ 4, remF1 = 17 ~ 20)
sumSpectra(MUD1d)
plotSpectra2D(MUD1d, which = 7, lvls = mylvls,
  main = "MUD1 Sample 7\\nRemoved Peaks: F2 2.5 ~ 4 & F1 17 ~ 20")

```





## Spectra2D
```{r, message=FALSE, warning = FALSE, error = FALSE}

data(MUD1)
str(MUD1)
sumSpectra(MUD1)

```






