#'
#' Plot Scores from a Multivariate Image Analysis (Tucker1) of a Spectra2D Object
#'
#' This function plots the scores from the multivariate image analysis
#' of a \code{\link{Spectra2D}} object.  A multivariate image analysis is the
#' same operation as a Tucker1 analysis.
#' You need to run \code{\link{miaSpectra2D}} before using this function.
#'
#' @param spectra An object of S3 class \code{\link{Spectra2D}}.
#'
#' @param mia A list as returned by \code{\link[ThreeWay]{pcasup1}}, with
#' class \code{pcasup1}.
#'
#' @param which An integer specifying two scores to plot.
#'
#' @param leg.loc Character; if \code{"none"} no legend will be drawn.
#' Otherwise, any string acceptable to \code{\link{legend}}.
#'
#' @param ellipse A character vector specifying the type of ellipses to be
#' plotted.  One of \code{c("both", "none", "cls", "rob")}.  \code{cls}
#' specifies classical confidence ellipses, \code{rob} specifies robust
#' confidence ellipses.  An ellipse is drawn for each group in 
#' \code{spectra$groups}, unless there are not enough data points (in
#' which case a warning is issued).
#'
#' @param tol A number describing the fraction of points to be labeled.
#' \code{tol = 1.0} labels all the points; \code{tol = 0.05} labels the most
#' extreme 5 percent.
#'
#' @param \dots Additional parameters to be passed to plotting functions.
#'
#' @return None.  Side effect is a plot.
#'
#' @author Bryan A. Hanson, DePauw University.
#'
#' @keywords hplot
#'
#' @seealso Please see \code{\link{miaSpectra2D}} for more information and examples.
#' 
#' @export
#'
#' @importFrom graphics plot
#' @importFrom ChemoSpecUtils .plotScores
#'
miaScores <- function(spectra, mia, which = c(1, 2), ellipse = "none", tol = "none", leg.loc = "topright", ...) {
	
	if (class(spectra) != "Spectra2D") stop("spectra argument was not a Spectra2D object")
	if (class(mia) != "pcasup1") stop("mia argument was not generated by miaSpectra2D")
	if (length(which) != 2L) stop("Please supply two scores to plot (argument 'which')")
    
	# See stackoverflow.com/a/46289614/633251 for the concepts re: argument handling
	
	# Use a sensible xlab and ylab if none provided
	args <- as.list(match.call()[-1])

	if (!("xlab" %in% names(args))) {
		xlab <- paste("Component", which[1], sep = " ")
		args <- c(args, list(xlab = xlab))
		}
	if (!("ylab" %in% names(args))) {
		ylab <- paste("Component", which[2], sep = " ")
		args <- c(args, list(ylab = ylab))
		}

	# Update & clean the argument list
	
	args <- c(args, list(use.sym = FALSE, pca = mia, pcs = which))
	args["mia"] <- NULL	
	do.call(.plotScores, args)
}